In [1]:
!pip install spotipy

Requirement already satisfied: spotipy in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (2.20.0)
Requirement already satisfied: redis>=3.5.3 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from spotipy) (4.3.4)
Requirement already satisfied: urllib3>=1.26.0 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from spotipy) (1.26.9)
Requirement already satisfied: six>=1.15.0 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from spotipy) (1.16.0)
Requirement already satisfied: requests>=2.25.0 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from spotipy) (2.27.1)
Requirement already satisfied: packaging>=20.4 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from redis>=3.5.3->spotipy) (21.3)
Requirement already satisfied: deprecated>=1.2.3 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from redis>=3.5.3->spotipy) (1.2.13)
Requirement already satisfied: async-timeout>=4.0.2 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from redis>=3.5.3->spotipy) (4.0.2)
Requirement already satisfied: wrapt<2,>=1.10 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from deprecated>=1.2.3->redis>=3.5.3->spotipy) (1.12.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from packaging>=20.4->redis>=3.5.3->spotipy) (3.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.25.0->spotipy) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.25.0->spotipy) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/mericgenc/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.25.0->spotipy) (2.0.4)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_stream = pd.read_json("StreamingHistory0.json")
df_stream.head()

            endTime         artistName trackName  msPlayed
0  2021-08-25 21:59  Son Feci Bisiklet     Torna    260467
1  2021-08-26 15:10  Son Feci Bisiklet  İstasyon    264480
2  2021-08-26 15:25  Son Feci Bisiklet   6patlar    279040
3  2021-08-26 15:29  Son Feci Bisiklet   Manidar    228960
4  2021-08-26 15:32  Son Feci Bisiklet        80    216800

In [4]:
df_stream['UniqueID'] = df_stream['artistName'] + ":" + df_stream['trackName']

df_stream.head()

,endTime,artistName,trackName,msPlayed,UniqueID
0,2021-08-25 21:59,Son Feci Bisiklet,Torna,260467,Son Feci Bisiklet:Torna
1,2021-08-26 15:10,Son Feci Bisiklet,İstasyon,264480,Son Feci Bisiklet:İstasyon
2,2021-08-26 15:25,Son Feci Bisiklet,6patlar,279040,Son Feci Bisiklet:6patlar
3,2021-08-26 15:29,Son Feci Bisiklet,Manidar,228960,Son Feci Bisiklet:Manidar
4,2021-08-26 15:32,Son Feci Bisiklet,80,216800,Son Feci Bisiklet:80

In [5]:
import json
from pandas.io.json import json_normalize

with open("YourLibrary.json") as json_data:
    data = json.load(json_data)

df_library = pd.DataFrame(data["tracks"])
df_library.head()

,artist,album,track,uri
0,Hozier,Hozier,Like Real People Do,spotify:track:39u3fJ8HNR4PLlGBirvjBi
1,LP,Lost on You,Into the Wild,spotify:track:6ZAJkghLCraONrwsyaNMvw
2,Flört,Cemiyette Pişiyoruz,Şakalar,spotify:track:0GbxcbGWZyccF5vGGp4yYF
3,Pink Floyd,The Wall [2011 - Remaster],"Prelude (The Wall Work In Progress, Pt. 1, 197...",spotify:track:1oyDmnMAXSZiq1kVpjB3xU
4,Opeth,Sorceress,The Ward,spotify:track:1nKzIXBZOaNlrIehmfxUlh

In [6]:
df_library["UniqueID"] = df_library["artist"] + ":" + df_library["track"]
df_library.head()

,artist,album,track,uri,UniqueID
0,Hozier,Hozier,Like Real People Do,spotify:track:39u3fJ8HNR4PLlGBirvjBi,Hozier:Like Real People Do
1,LP,Lost on You,Into the Wild,spotify:track:6ZAJkghLCraONrwsyaNMvw,LP:Into the Wild
2,Flört,Cemiyette Pişiyoruz,Şakalar,spotify:track:0GbxcbGWZyccF5vGGp4yYF,Flört:Şakalar
3,Pink Floyd,The Wall [2011 - Remaster],"Prelude (The Wall Work In Progress, Pt. 1, 197...",spotify:track:1oyDmnMAXSZiq1kVpjB3xU,"Pink Floyd:Prelude (The Wall Work In Progress,..."
4,Opeth,Sorceress,The Ward,spotify:track:1nKzIXBZOaNlrIehmfxUlh,Opeth:The Ward

In [7]:
new = df_library["uri"].str.split(":", expand = True)
new.head()

         0      1                       2
0  spotify  track  39u3fJ8HNR4PLlGBirvjBi
1  spotify  track  6ZAJkghLCraONrwsyaNMvw
2  spotify  track  0GbxcbGWZyccF5vGGp4yYF
3  spotify  track  1oyDmnMAXSZiq1kVpjB3xU
4  spotify  track  1nKzIXBZOaNlrIehmfxUlh

In [8]:
df_library["track_uri"] = new[2]
df_library.head()

,artist,album,track,uri,UniqueID,track_uri
0,Hozier,Hozier,Like Real People Do,spotify:track:39u3fJ8HNR4PLlGBirvjBi,Hozier:Like Real People Do,39u3fJ8HNR4PLlGBirvjBi
1,LP,Lost on You,Into the Wild,spotify:track:6ZAJkghLCraONrwsyaNMvw,LP:Into the Wild,6ZAJkghLCraONrwsyaNMvw
2,Flört,Cemiyette Pişiyoruz,Şakalar,spotify:track:0GbxcbGWZyccF5vGGp4yYF,Flört:Şakalar,0GbxcbGWZyccF5vGGp4yYF
3,Pink Floyd,The Wall [2011 - Remaster],"Prelude (The Wall Work In Progress, Pt. 1, 197...",spotify:track:1oyDmnMAXSZiq1kVpjB3xU,"Pink Floyd:Prelude (The Wall Work In Progress,...",1oyDmnMAXSZiq1kVpjB3xU
4,Opeth,Sorceress,The Ward,spotify:track:1nKzIXBZOaNlrIehmfxUlh,Opeth:The Ward,1nKzIXBZOaNlrIehmfxUlh

In [9]:
df_tableau=df_stream.copy()
df_tableau.head()

,endTime,artistName,trackName,msPlayed,UniqueID
0,2021-08-25 21:59,Son Feci Bisiklet,Torna,260467,Son Feci Bisiklet:Torna
1,2021-08-26 15:10,Son Feci Bisiklet,İstasyon,264480,Son Feci Bisiklet:İstasyon
2,2021-08-26 15:25,Son Feci Bisiklet,6patlar,279040,Son Feci Bisiklet:6patlar
3,2021-08-26 15:29,Son Feci Bisiklet,Manidar,228960,Son Feci Bisiklet:Manidar
4,2021-08-26 15:32,Son Feci Bisiklet,80,216800,Son Feci Bisiklet:80

In [10]:
df_tableau["In Library"]=""

In [11]:
df_tableau['In Library'] = np.where(df_tableau["UniqueID"].isin(df_library["UniqueID"]).tolist(), 1, 0)

In [12]:
df_tableau = pd.merge(df_tableau, df_library[["album","UniqueID","track_uri"]], how="left", on=["UniqueID"])

In [13]:
df_tableau.head()

,endTime,artistName,trackName,msPlayed,UniqueID,In Library,album,track_uri
0,2021-08-25 21:59,Son Feci Bisiklet,Torna,260467,Son Feci Bisiklet:Torna,0,NaN,NaN
1,2021-08-26 15:10,Son Feci Bisiklet,İstasyon,264480,Son Feci Bisiklet:İstasyon,0,NaN,NaN
2,2021-08-26 15:25,Son Feci Bisiklet,6patlar,279040,Son Feci Bisiklet:6patlar,0,NaN,NaN
3,2021-08-26 15:29,Son Feci Bisiklet,Manidar,228960,Son Feci Bisiklet:Manidar,0,NaN,NaN
4,2021-08-26 15:32,Son Feci Bisiklet,80,216800,Son Feci Bisiklet:80,0,NaN,NaN

In [14]:
import spotipy
CLIENT_ID = 'Your_Client_ID'
CLIENT_SECRET = 'Your_Client_Secret'

In [15]:
auth_manager = spotipy.SpotifyClientCredentials(client_id=CLIENT_ID,
                                        client_secret=CLIENT_SECRET,)

sp = spotipy.Spotify(client_credentials_manager=auth_manager)

In [16]:
genres = []
for a in df_tableau['artistName']:
    genres.append(sp.search(a, type='artist')['artists']['items'][0]['genres'])
df_tableau['genres'] = genres

In [17]:
df_tableau.head()

,endTime,artistName,trackName,msPlayed,UniqueID,In Library,album,track_uri,genres
0,2021-08-25 21:59,Son Feci Bisiklet,Torna,260467,Son Feci Bisiklet:Torna,0,NaN,NaN,[turkish rock]
1,2021-08-26 15:10,Son Feci Bisiklet,İstasyon,264480,Son Feci Bisiklet:İstasyon,0,NaN,NaN,[turkish rock]
2,2021-08-26 15:25,Son Feci Bisiklet,6patlar,279040,Son Feci Bisiklet:6patlar,0,NaN,NaN,[turkish rock]
3,2021-08-26 15:29,Son Feci Bisiklet,Manidar,228960,Son Feci Bisiklet:Manidar,0,NaN,NaN,[turkish rock]
4,2021-08-26 15:32,Son Feci Bisiklet,80,216800,Son Feci Bisiklet:80,0,NaN,NaN,[turkish rock]

In [18]:
df_tableau_expanded = df_tableau.explode('genres')
df_tableau_expanded.index = range(0,len(df_tableau_expanded))
df_tableau_expanded.tail()

,endTime,artistName,trackName,msPlayed,UniqueID,In Library,album,track_uri,genres
24071,2022-08-26 15:36,Dream Theater,Pull Me Under,493933,Dream Theater:Pull Me Under,0,NaN,NaN,progressive metal
24072,2022-08-26 15:44,Dream Theater,As I Am,467826,Dream Theater:As I Am,0,NaN,NaN,neo classical metal
24073,2022-08-26 15:44,Dream Theater,As I Am,467826,Dream Theater:As I Am,0,NaN,NaN,progressive metal
24074,2022-08-26 20:24,Dream Theater,This Dying Soul,530510,Dream Theater:This Dying Soul,0,NaN,NaN,neo classical metal
24075,2022-08-26 20:24,Dream Theater,This Dying Soul,530510,Dream Theater:This Dying Soul,0,NaN,NaN,progressive metal

In [19]:
dict_genre = {}
track_uris = df_library['track_uri'].to_list()

for t_uri in track_uris:
    dict_genre[t_uri] = {'artist_uri': "", "genres":[]}
    a_uri = sp.track(t_uri)["artists"][0]["uri"].split(":")[2]
    a_name = sp.track(t_uri)['artists'][0]['name']
    t_name = sp.track(t_uri)['name']
    dict_genre[t_uri]['artist_uri'] = a_uri
    dict_genre[t_uri]['artist_name'] = a_name
    dict_genre[t_uri]['track_name'] = t_name

    a_genres = sp.artist(a_uri)['genres']
    dict_genre[t_uri]['genres'] = a_genres

In [20]:
df_genre = pd.DataFrame.from_dict(dict_genre, orient='index')
df_genre.insert(0, 'track_uri', df_genre.index)
df_genre.reset_index(inplace=True, drop=True)

df_genre.head()

,track_uri,artist_uri,genres,artist_name,track_name
0,39u3fJ8HNR4PLlGBirvjBi,2FXC3k01G6Gw61bmprjgqS,"[irish singer-songwriter, pop]",Hozier,Like Real People Do
1,6ZAJkghLCraONrwsyaNMvw,0J7U24vlOOIeMpuaO6Q85A,"[la pop, women's music]",LP,Into the Wild
2,0GbxcbGWZyccF5vGGp4yYF,0ou1EkRCAJcfRv2P1qKVPo,"[turkish alternative, turkish alternative rock...",Flört,Şakalar
3,1oyDmnMAXSZiq1kVpjB3xU,0k17h0D3J5VfsdmQ1iZtE9,"[album rock, art rock, classic rock, progressi...",Pink Floyd,"Prelude (The Wall Work In Progress, Pt. 1, 197..."
4,1nKzIXBZOaNlrIehmfxUlh,0ybFZ2Ab08V8hueghSXm6E,"[alternative metal, metal, progressive death m...",Opeth,The Ward

In [21]:
df_genre_expanded = df_genre.explode('genres')
df_genre_expanded.index = range(0,len(df_genre_expanded))
df_genre_expanded.head()

,track_uri,artist_uri,genres,artist_name,track_name
0,39u3fJ8HNR4PLlGBirvjBi,2FXC3k01G6Gw61bmprjgqS,irish singer-songwriter,Hozier,Like Real People Do
1,39u3fJ8HNR4PLlGBirvjBi,2FXC3k01G6Gw61bmprjgqS,pop,Hozier,Like Real People Do
2,6ZAJkghLCraONrwsyaNMvw,0J7U24vlOOIeMpuaO6Q85A,la pop,LP,Into the Wild
3,6ZAJkghLCraONrwsyaNMvw,0J7U24vlOOIeMpuaO6Q85A,women's music,LP,Into the Wild
4,0GbxcbGWZyccF5vGGp4yYF,0ou1EkRCAJcfRv2P1qKVPo,turkish alternative,Flört,Şakalar

In [22]:
df_tableau.to_csv('tables/MySpotifyDataTable.csv')
df_tableau_expanded.to_csv('tables/MySpotifyExpandedTable.csv')
df_genre_expanded.to_csv('tables/GenresExpandedTable.csv')

print('done')

done